#
# Makefile
#
# Erzeugt die Beispiel-Programme zur Systemprogrammierung Teil 5
# Beispiel: make io
#
# Autor: H.Drachenfels
# Erstellt am: 21.5.2020
#

CXX=g++
CXXFLAGS = -g -W -Wall -std=c++11 -pedantic

